[llvm]
targets = "X86"
download-ci-llvm = false  # Otherwise, can't specify target

[build]
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnu", "i686-unknown-linux-musl"]
target = ["i686-unknown-linux-musl"]
extended = true
tools = ["cargo", "clippy", "rustfmt"]

[target.i686-unknown-linux-musl]
cc = "/root/x-tools/i686-pc-linux-musl/bin/i686-pc-linux-musl-gcc"
cxx = "/root/x-tools/i686-pc-linux-musl/bin/i686-pc-linux-musl-g++"
ar = "/root/x-tools/i686-pc-linux-musl/bin/i686-pc-linux-musl-gcc-ar"
ranlib = "/root/x-tools/i686-pc-linux-musl/bin/i686-pc-linux-musl-gcc-ranlib"
linker = "/root/x-tools/i686-pc-linux-musl/bin/i686-pc-linux-musl-gcc"
musl-root = "/root/x-tools/i686-pc-linux-musl/i686-pc-linux-musl/sysroot"
